In [ ]:
from os import (
    getenv,
)
from glob import glob
from typing import (
    Dict,
    List,
    Any,
)
from json import (
    dumps,
    dump,
    loads,
    load,
)
import streamlit as st
from openai.types.chat import (
    ChatCompletionMessageToolCall,
    ChatCompletionMessageToolCallParam,
    ChatCompletionMessage,
    ChatCompletionSystemMessageParam,
)

In [1]:
class Test():

    def __init__(self) -> None: pass

    def _method(self) -> str:
        return "Hello!"
    
    def use_dunder(
        self,
        name: str,
    ) -> str:
        return self.__getattribute__(name)()
    

t = Test()

t.use_dunder("_method")

'Hello!'

In [ ]:
ChatCompletionMessageToolCallParam()
ChatCompletionMessageToolCall()

In [4]:
loads(dumps({}))

{}

In [6]:
loads(r"{}")

{}

In [3]:
param = ChatCompletionMessageToolCallParam(id="", function="f", type="function")

In [8]:
call = ChatCompletionMessageToolCall(id="", type="function", function="")

ValidationError: 1 validation error for ChatCompletionMessageToolCall
function
  Input should be a valid dictionary or instance of Function [type=model_type, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type

In [2]:
from pandas import (
    DataFrame,
    read_excel,
    Series,
)
import matplotlib.pyplot as plt

In [3]:
results = read_excel('.\\tests\\rag\\results\\rag_results.xlsx', index_col=0)
results

,nv_accuracy,nv_context_relevance,nv_response_groundedness
name,,,
baseline_31-03-25_12-33,0.035714,0.000000,0.000000
31-03-25_12_36,0.278571,0.585714,0.478571
30-04-25_11-34,0.271429,0.614286,0.700000
30-04-25_11-35,0.257143,0.621429,0.650000
30-04-25_11-51,0.278571,0.592857,0.671429
30-04-25_14-08,0.472222,0.750000,0.732143
30-04-25_14-17,0.257143,0.628571,0.628571
20-05-25_16-58,0.264286,0.542857,0.800000
20-05-25_17-07,0.314286,0.578571,0.800000
20-05-25_17-24,0.285714,0.535714,0.792857
21-05-25_14-51,0.364286,0.585714,0.735714
21-05-25_14-57,0.414286,0.578571,0.742857
22-05-25_11-53-without-filter,0.200000,0.464286,0.635714
22-05-25_12-05-without-filter,0.207143,0.478571,0.714286
27-05-25_13-55-top1-only,0.364286,0.492857,0.664286
27-05-25_17-33-rdf-only,0.257143,0.257143,0.292857
28-05-25_07-45-html-only,0.378571,0.535714,0.657143
28-05-25_15-38,0.400000,0.535714,0.714286
03-06-25_09-39-with-keyword,0.542857,0.678571,0.935714
03-06-25_09-44-with-keyword,0.492857,0.678571,0.885714
03-06-25_10-08,0.407143,0.585714,0.671429
03-06-25_10-14,0.400000,0.535714,0.700000
03-06-25_10-51,0.478571,0.685714,0.892857
03-06-25_10-57,0.485714,0.742857,0.892857
03-06-25_11-04,0.450000,0.664286,0.885714

In [4]:
def key(name: str) -> str:
    return f'{name[:8]}, {name[15:]}'

In [5]:
aggregated = results.groupby(key).aggregate('mean').sort_values(by='nv_accuracy').reset_index()
aggregated

,name,nv_accuracy,nv_context_relevance,nv_response_groundedness
0,"baseline, 25_12-33",0.035714,0.000000,0.000000
1,"22-05-25, without-filter",0.203571,0.471429,0.675000
2,"27-05-25, rdf-only",0.257143,0.257143,0.292857
3,"31-03-25,",0.278571,0.585714,0.478571
4,"20-05-25,",0.288095,0.552381,0.797619
5,"30-04-25,",0.307302,0.641429,0.676429
6,"27-05-25, top1-only",0.364286,0.492857,0.664286
7,"28-05-25, html-only",0.378571,0.535714,0.657143
8,"21-05-25,",0.389286,0.582143,0.739286
9,"28-05-25,",0.400000,0.535714,0.714286
10,"03-06-25,",0.444286,0.642857,0.808571
11,"03-06-25, with-keyword",0.517857,0.678571,0.910714

In [6]:
keys: list[str] = [
    'baseline, 25_12-33',
    '22-05-25, without-filter',
    '20-05-25, ',
    '21-05-25, ',
    '03-06-25, with-keyword',
]

In [7]:
xs = [
    'baseline',
    'basic',
    'filtered',
    'improved html',
    'final',
]

In [8]:
filtered = aggregated[[name in keys for name in aggregated['name']]]

In [9]:
fig, ax = plt.subplots(1, 1, figsize=(10, 5))
ax.plot(xs, filtered['nv_accuracy'], label='Accuracy')
ax.plot(xs, filtered['nv_context_relevance'], label='Context Relevance')
ax.plot(xs, filtered['nv_response_groundedness'], label='Response Groundedness')
ax.legend()
ax.set_ylim(0, 1)
ax.set_yticks([i/10 for i in range(11)])
ax.grid()

plt.savefig('test.png')

In [38]:
glob('.\\tests\\rag\\results\\*')

['.\\tests\\rag\\results\\rag_20-05-25_16-58.xlsx',
 '.\\tests\\rag\\results\\rag_20-05-25_17-07.xlsx',
 '.\\tests\\rag\\results\\rag_20-05-25_17-24.xlsx',
 '.\\tests\\rag\\results\\rag_21-05-25_14-51.xlsx',
 '.\\tests\\rag\\results\\rag_21-05-25_14-57.xlsx',
 '.\\tests\\rag\\results\\rag_22-05-25_11-53-without-filter.xlsx',
 '.\\tests\\rag\\results\\rag_22-05-25_12-05-without-filter.xlsx',
 '.\\tests\\rag\\results\\rag_27-05-25_13-55-top1-only.xlsx',
 '.\\tests\\rag\\results\\rag_27-05-25_17-33-rdf-only.xlsx',
 '.\\tests\\rag\\results\\rag_28-05-25_07-45-html-only.xlsx',
 '.\\tests\\rag\\results\\rag_30-04-25_11-34.xlsx',
 '.\\tests\\rag\\results\\rag_30-04-25_11-35.xlsx',
 '.\\tests\\rag\\results\\rag_30-04-25_11-51.xlsx',
 '.\\tests\\rag\\results\\rag_30-04-25_14-08.xlsx',
 '.\\tests\\rag\\results\\rag_30-04-25_14-17.xlsx',
 '.\\tests\\rag\\results\\rag_31-03-25_12-36.xlsx',
 '.\\tests\\rag\\results\\rag_baseline_31-03-25_12-33.xlsx',
 '.\\tests\\rag\\results\\rag_results.xlsx']

In [45]:
results = read_excel('.\\tests\\rag\\results\\rag_28-05-25_07-45-html-only.xlsx')

In [46]:
semic = results[results['user_input'].str.startswith('[SEMIC]')]

In [47]:
oslo = results[results['user_input'].str.startswith('[OSLO]')]

In [48]:
semic[['nv_accuracy', 'nv_response_groundedness', 'nv_context_relevance']].mean()

nv_accuracy                 0.791667
nv_response_groundedness    1.000000
nv_context_relevance        1.000000
dtype: float64

In [49]:
oslo[['nv_accuracy', 'nv_response_groundedness', 'nv_context_relevance']].mean()

nv_accuracy                 0.293103
nv_response_groundedness    0.586207
nv_context_relevance        0.439655
dtype: float64